name: Earth Engine Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace 'x' with your desired Python version

    - name: Install Earth Engine Python API
      run: |
        pip install earthengine-api

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Save Earth Engine credentials
      run: |
        echo "${{ secrets.EARTH_ENGINE_CREDENTIALS }}" > treed-world-e2841ea9ba8b.json

    - name: Set up Google Cloud SDK with Service Account key
      run: |
        gcloud auth activate-service-account --key-file=treed-world-e2841ea9ba8b.json

    - name: Run Earth Engine script
      run: python script.py  # Assuming the script.py is in the main directory

    - name: Move exported image as an artifact
      run: |
        mkdir -p artifacts
        mv exported_image.tif artifacts/
      continue-on-error: true

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: exported-image
        path: artifacts/exported_image.tif
